BEGIN TRANSACTION;
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision Fixed 4MP IP Camera','IP Camera',2800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Weather Box 20X16X10',NULL,2400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Steel Pole',NULL,200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Coaxial Cable',NULL,10.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Yeaster S20 IPPBX System (Exclu. Addons)','20 Users, 10 Concurrent Calls, Up to 4 FXS/FXO/BRI Ports, Up to 1 GSM/3G/4G Channel, 20 VoIP Trunks',16000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Grandstream GS-WP820',NULL,7600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('installation of Cathexis Wall','Installation and configuration of Cathexis Server, screen and layouts',3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hybrid PBX','Supply and Installation of Panasonic KX-TES824 Advanced HyBrid PABX Telephone System with 8Co Lines and 24 Extensions',18500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision ClearVu 2MP Cameras 8 Camera set','8 Cameras, 1TB, PSU inclusive',6000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Nexuss Camera',NULL,1.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dahua NVR 24 Channel without HDD',NULL,3250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dahua IP 4MP Fixed',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('FTP Cat6 Cable','500 metre Cable Roll',7500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('ClearVue Fence','Installation  per meter',900.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Game Fence wire (Smaller Boxes)','Game wire with small boxes per metre',80.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Razor wire flat with electric fence','All materials plus labor',150.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Game Wire (Big boxes)','1.8m Height, 300mm Boxes, 2mm wire thickness',70.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Razor Wire Round','Per roll of 10 metres',450.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Round Razor wire with Electric Fence','All materials plus labour',160.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Electric Fence','6 Lines, alarm system and all labour',85.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Barbed wire',NULL,55.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('D5 Gate Motors',NULL,8000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('POE Injector',NULL,500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('8 Port POE Auxiliary Network Switch','Powers on end nodes that support POE',3000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Cabinet 12U',NULL,6000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Single Mode Optic Fibre',NULL,25.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Media Converters',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dahua Home Kit 4CH','4 Cameras 20 meters Cable Per Camera 1 DVR',4500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Video Connector (BNC)','Analogue Connectors',25.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision Low Power Solar Wifi/4G Fixed','Solar Powered',6500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('hikvision Wireless Camera 8','Wireless 8 Cameras, NVR, 1TB HDD,',14500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision Wireless 4 Channels,','4 Wireless Cameras, 1 TB HDD, NVR',9000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('HiKvision Home Kit 8 Channels',NULL,6500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dahua Homekit 8 Channel','8 Cameras 1 DVR No HDD',6500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision Home Kit 4 Channel','4 Cameras 1TB HDD 1 DVR',4800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link Switch 8 Port',NULL,700.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Data Shark PA70007 Ethernet Network tool','DataShark PA70007 Ethernet Network Tool Kit w/RJ45/RJ11 Crimp Tool, Stripper.',2800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision PTZ 100m IP',NULL,9000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision PTZ 150m IP',NULL,11400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision PTZ 100m Analogue',NULL,7200.0,0.0);
COMMIT;
