INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Wavelink AX3000','Wifi 6, Dual Band outdoor Router',9000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Mikrotik RB950','Manage user traffic and accounting for clients',6000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Subscription on Purchase',NULL,800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Installation & CCTV System Setup','Includes Starlink unit installation, camera cable laying (up to 120 meters), DVR configuration, remote view setup, alignment, testing, training, commissioning and local transport.',6500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 4Mp Bullet Camera',NULL,3250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 4mp Dome Camera',NULL,3150.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('POE Switches SFP 10 Port',NULL,7500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('SFP Modules 1G',NULL,2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Ceiling Mount Access Points',NULL,3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('LAN Cleanup',NULL,2000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Labour',NULL,23985.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cisco 891F Gigabit Integrated Services Router',NULL,8500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('HP ProLiant DL 380P G8','RAM 64GB, comes with 256GB x 2 SSD, 1TB x 2 HDD with an option to upgrade',35000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cabinet 16U Cabinet',NULL,15000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Logistic Eastern',NULL,20.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Logistics Northern',NULL,1460.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Logistics Western',NULL,20.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Logistics Southern',NULL,20.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Logistics Lusaka',NULL,20.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Logistics Copperbelt',NULL,20.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Project Hire',NULL,800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Projector White Screen',NULL,500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cherry Picker',NULL,1000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Operator Cherry Picker',NULL,200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fiber Installation',NULL,35.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Preconfigured inclusive of Installation and 1 Month Subscription',NULL,16500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Monthly Subscription',NULL,3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Mikrotik WAP',NULL,3000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('4U Network Cabinet',NULL,2250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dahua 8 Port POE Switch',NULL,1300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Access Points (Indoor)',NULL,2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dahua CAT6 ethernet Cable 305m',NULL,3200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('10G (RJ45) Electrical','Support 10Gbase-T / 5Gbase-T / 2.5Gbase-T / 1000base-T on line port • Support 10Gbase-R on host port • Hot-pluggable SFP footprint • Compact RJ-45 connector assembly • RoHS compliant and lead-free • Single +3.3V power supply • 10 Gigabit Ethernet over Cat 6a cable • Ambient Operating temperature: 0°C to +60°C',5500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Rental','Rental of Starlink Equipment plus Service for 6 months. Additional 6 months approval required.',1800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Rental Starlink Once Off Installation/Decommission Cost','Installation of Starlink at location for Rental. This includes accessories',2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dahua 16 CH NVR',NULL,12500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('6TB HDD Security Hard Drive',NULL,6800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dahua CAT6 Ethernet Cable - 305m',NULL,3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation Accessories - (RJ45/Jackets/Cable Ties/Trunking)',NULL,2250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dahua 4MP Outdoor Network Bullet Camera',NULL,3600.0,0.0);
