INSERT INTO customers (name,email,phone,address) VALUES ('David Mwape',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('SOS Secondary School',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Chienge District Health Office',NULL,NULL,'Chienge, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mwandi Town Council',NULL,NULL,'Mwandi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Nelly Musonda Phiri',NULL,'''+260-762130442','kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Benjamin Kafwembe',NULL,NULL,'Chililabombwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Charles Chisenga',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('inq.Digital Zambia Limited',NULL,NULL,'Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Peter Bwanali',NULL,'''+260-977384341','Riverside, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Bazil Technology',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Airtel Zambia',NULL,'''+260-978981829','P. O. Box 32000,, Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('China Geo-Engineering Corporation',NULL,NULL,'Nakonde, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mwandu Mwelwa',NULL,NULL,'Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Felix Boonda',NULL,'''+260-0968886447','Mufulira, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Musiwa Ikafa',NULL,'''+260-966399933',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Mrs. V M Lwanga',NULL,'''+260-0977777679','Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mafinga Town Council',NULL,NULL,'Mafinga, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mufungo Milling',NULL,NULL,'Second Class, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Chibesakunda & Co',NULL,NULL,'Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Silvana LoDrago',NULL,'''+260-0961191268','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Sepiso',NULL,NULL,'Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. C Chimbanga',NULL,NULL,'Kitwe');
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 2MP Camera Analogue Cameras',NULL,400.0,350.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('CCTV Cellular Inqmega','Solar Camera with Sim Card',4100.0,3500.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Bullet camera Hikvision 4mp IP',NULL,3000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('16  channel Hikvision NVR with 2TB',NULL,9500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cabinet Network 12U',NULL,5500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Electrical Cable 2 core','0.5mm^2, 2 cores, PVC Sheath, maximum operating Temp +70C, Voltage rating 300V',15.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Rawl Bolts & Nuts',NULL,120.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Pole',NULL,75.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Soft Wire',NULL,10.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hard Drive 1TB','Recording of Storage',1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation & Configuration',NULL,12000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation Accessories','Rawl Bolts, nails, Insulation tape, cable ties',2000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Conduit Pipes','3 meters per pipe',35.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunk PVC 40x25','3 meters',85.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('NVR Stand','Mount the NVR',500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Weather Junction Box','IP55, 100x100x50mm',90.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cambium Radios Pair 450i','point 2 point Radios',8000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision Analogue Set of 4 with 8 Channel DVR',NULL,6500.0,0.0);
