INSERT INTO customers (name,email,phone,address) VALUES ('Garry Siamwanza','garrysiamwanza@gmail.com',NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Ms. Luwi Luvweyi',NULL,NULL,'Solwezi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Winfridah Mofu',NULL,'''+260971260038','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Brian Chondoka',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('NEBCON Executive Lodge',NULL,'260 963472924','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('National Assembly of Zambia','info@parliament.gov.zm','''+260 211 292425-36','Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Dr. Kangwa',NULL,'0963472936',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Milford Lodge',NULL,'0961667546','Nkana East, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Shawn Ge',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Chill Out Restaurant and Bar',NULL,NULL,'Riverside, Chingola, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Copperbelt Energy Corporation','siamwanzag@cec.com.zm','''+260979074258','P O Box 20819, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Erwins Kanyama',NULL,'''+260966195362','Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Green Acre Mining Limited',NULL,'''+260765960608','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Customer',NULL,NULL,'Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mutule Holdings',NULL,'''+260968144429','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mwemo Investment Limited','mwemoinvestments02@gmail.com','''+260967252154','Dr Aggrey road,, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Kennedy Chitundu','chitunduchitunduk@gmail.com','''+260961606122','Mufulira, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Ms. Tapiwa Kaemba',NULL,'0977843246','Kalulushi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('BL&D Plant Hire and Sales',NULL,'0964538765','Kitwe/Ndola Road, Kamfinsa, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('AEL Intelligent Blasting','japhet.phiri@aeciworld.com','0960924054','Mufulira, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Asenga Executive Lodge',NULL,'096 0388348','Mufulira, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Zambia Revenue Authority','dennis.chulu@hrc.org.zm',NULL,'Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Ms. Sharon Nkunika',NULL,'0977872459','Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Ms. Angela Chirwa',NULL,NULL,'Mufulira, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Chanda Lubindo','chandalubindo@yahoo.com',NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Amit Sharma','amit.sharma@bmrcinternational.ae',NULL,'United Arab Emirates');
INSERT INTO customers (name,email,phone,address) VALUES ('Zambia Public Procurement Authority',NULL,NULL,'Off Alick Nkhata Road, Longacres, Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Libuku',NULL,NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('National','nancyn@nmc.co.zm','''+260-211229548','Lilayi Rd, Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Zambia Air Force',NULL,NULL,'Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Sekelela Farms',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Chienge Town Council',NULL,NULL,'Chiengi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Egeni Mwewa',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mansa Municipal Council',NULL,NULL,'Mansa, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Ebenezer Classics Fashionz',NULL,NULL,'Nkana kitwe, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Martin Sichembe',NULL,'0977505033','Kalulushi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Nannah Nkunika','nannahnkunika@gmail.com','''+260979414659','Lusaka West, Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Chimwewe Kabamba',NULL,NULL,'Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Sharon Nkunika','sharonkunika@gmail.com','''+260 977872459','Mbereshi Way, Leopard’s hill road, Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mpifi Ltd',NULL,'260 972526683','Chililabombwe, Zambia');
