INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Beetle Analogue',NULL,1200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision DVR 16 Ch 1080p','16 Channel DVR  1TB Storage  Power Supply Unit CCTV 18-Way 12V',8500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Bullet 25m 2MP ColorVu Smart',NULL,800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('RG59 + Power Cable',NULL,8.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('CCTV Connector Power Jack DC',NULL,25.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('CCTV Enclosure Box 100x100x50',NULL,115.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link Archer 50 Wireless Router',NULL,2850.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Installation',NULL,3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Sollatek AVS','Protecting units from Damage',1800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision Solar Camera with 4G/Wifi','High quality imaging with 4 MP resolution Standalone with solar panel and built-in battery Support human and vehicle detection Provide real-time security via built-in two-way audio Water and dust resistant (IP67) Support 4G (LTE-TDD/LTE-FDD/TD-SCDMA) communication',6500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Vertex 160VX Radios','LIGHT WEIGHT AND COMPACT SIZE16 CHANNEL CAPACITY5 WATTS POWER OUTPUT(Selectable to 1 Watt)MIL-STD 810 C/D/ERUGGED CONSTRUCTIONLOUD, CLEAR AUDIO OUTPUT12.5/25 kHz BANDWIDTHPROGRAMMABLE BY CHANNELCTCSS/DCS ENCODE + DECODEDTMF ANIDUAL 2-TONE DECODEMULTI-MODE SCAN(incl. Dual Watch, Priority, Follow-Me)ARTS" (Auto-Range Transponder System)BCLO, BTLO, AND TOT FUNCTIONSTX/RX BATTERY SAVER CIRCUITPC PROGRAMMINGRADIO-TO-RADIO CLONING',6000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Vertex VX 9000 Repeater','Large 2 digit numeric display 6 buttons (programmable - dual function) 25 pin DB25 Rear Accessory Connector Frequency Stability 1.5ppm VHF and 1.5ppm UHF 19" rack mount - 2 U high 13.6 volt nominal DC (additional extra FP-31 220 - 240V AC internal PSU) Type ''N'' Connector for Tx and BNC for Rx antenna connections',87500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Kodak Solar Inverter 3.2KW','Inverter 24V with Exide Tubular Battery-Acid',15000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Solar Panels 550w',NULL,4200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('DC Cables Red & Black','6mm',95.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Iron Bars stands for Panel','Fabricating brackets to hold Solar Panels',250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Solar System','Installation and Delivery of Solar System',9990.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('UTP Cat 6 Cable','Network Cable Drum of 305m',3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Floating Shelf',NULL,600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Lithium Ion Batteries 5.1kw',NULL,32000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Inverter HYBRID 5.5kVA',NULL,15000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision NVR with Monitor','''-Inclusive of 4 Cameras and 1TB HDD -11.6-inch LCD display and HDMI output -Up to 4-ch@4 MP (15 fps)/4-ch@1080p (30 fps) decoding capability  -Up to 4-ch network camera inputs, connectable with Wi-Fi cameras  -Standing or wall-mounted installation',9800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Monitoring Screeen 24"',NULL,2000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of CCTV','Installation, configuration and comissioning',4000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP-Link ARCHERAX20 - AX1800','Dual Band Gigabit Router, New WI-FI 6 Tech, High performance router',3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Maintenance & Service','Attend to faults, cleaning Cameras and rebuild of HDD storage',1650.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision Solar Powered 4G Camera - DS-2XS2T47G1','4 MP solar-powered security camera with 24/7 color imaging, human detection, two-way audio, and 4G connectivity. IP67-rated and typhoon-resistant, it’s built for reliable, off-grid security in remote locations.',6000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Camera Restoration to working state',NULL,250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Video Balun','Transmission of CCTV signal over UTP Pair',65.0,50.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Maintenance and Service of Cameras','''- Physical Inspection - Cleaning  - Functional Testing - Configuration & Network Check  - Report',130.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 4 Channel eDVR with SSD','DVR 4X Cameras',6200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Home CCTV','Installation, Configuration, a Month Support',2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of an Analogue CCTV Camera',NULL,400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 8 Channel eDVR with SSD Kit','8 Cameras eDVR',8500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Camera Installation',NULL,400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Access Point Installation',NULL,600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Subscription Monthly','including Support',2100.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Intruder Alarm System','4 X Motion Detector, 3 x Door Close, 1 sms Communicator',9000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('HIkvision 32 Channel Analogue','32 Channel DVR with no HardDrive',10700.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision Analogue Clearvue 60mm Camera',NULL,750.0,0.0);
