INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('300KG Door Magnetic Lock plus Z Bracket',NULL,3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Automatic Door Closer',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('PVC Conduit Joint',NULL,200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('PVC Weather Proof Box',NULL,150.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Data Network',NULL,300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunking 16mmx25mm',NULL,300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Bullet 25m 2MP ColorVu Smart Hybrid+MIC Mid Level',NULL,850.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('CCTV Connector BNC',NULL,35.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('ADSS 48 Core Fibre Cable',NULL,32.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dome Joint',NULL,1200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Anchoring and securing Fiber',NULL,15.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Splicing',NULL,90.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Switch Managed',NULL,10000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Ubiquiti U6 Pro Wireless AP','Indoor, dual-band WiFi 6 access point that can support over 300 clients with its 5.3 Gbps aggregate throughput rate.',7000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Configuration of CCTV','Professional configuration of the network',400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Mounting Brackets',NULL,500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunking & Conduits',NULL,250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Relocation of Starlink',NULL,600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('48 Core Single Mode Fiber Cable',NULL,48.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Outdoor Weather Fiber Termination Boxes',NULL,2800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cisco c1000-8FP-2G-L Switch',NULL,65000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('GLC-LH-SMD CISCO SFP Module',NULL,2800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cat6 UTP Outdoor Ethernet cable',NULL,32.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('C9124AXE Cisco Outdoor wireless Antenna with 4 Antennas',NULL,58000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Radwin 2000','Point-to-Point(PTP)',10000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Coaxial Cable RG59 with Power 2×1.0mm',NULL,18.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Outdoor UTP CAT6 Cable',NULL,25.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Transport',NULL,250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation and Repair',NULL,250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('150*40mm 0.8mm Metallic cable tray',NULL,2300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('40mm Cable tray joint kit',NULL,175.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('100*40mm 0.8mm Metallic cable tray',NULL,1900.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('RJ45 Double Wall box complete with insert',NULL,200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cambium Client Radios',NULL,12500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cambium Access Point Radio',NULL,25000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('HP workstation with 64gb ram',NULL,34000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hisense 75" inch TV',NULL,38000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Screen 86" Interactive / Projector Hikvision','DS-D5B86RB/D, DS-D5C86RB/D',120000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Radios (Client Radios)',NULL,2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Access Point Radios',NULL,3500.0,0.0);
