INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Industrial insulation tapes',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('HDMI 10m',NULL,1400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('13 Amps Top Plug',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('1.5KVA UPS',NULL,3000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('55'''' Monitor Screen with wall mounts & HDMI',NULL,12500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fabrication work',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Contingency',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Labor and Configuration',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('24 core fiber single mode',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Remote support 10hr monthly (monthly)',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('7 days per quarter on site maintaince/ breakdowns excluding food, accomodation and transport',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('PVC couplings 25mm',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP-Link 2.4GHz 300Mbps 9dBi CPE CPE210','Radio to be used to for point to point connection',3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP-Link 16-Port Gigabit Rackmount Switch TL-SG1016',NULL,2800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('RJ45 wall mount box',NULL,180.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunking 40mm X 40mm',NULL,140.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 8 CH NVR',NULL,7000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('42 Inch Display Screen',NULL,10000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link Wireless Router',NULL,900.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('UBIQUITI NANOSTATION M2','150+ Mpbs real outdoor throughput and up to 15km+ range',4860.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cabinet 24U',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Networking Router',NULL,6000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dell Laptop E5530','Refurbished Laptop',3000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision NVR 16 Channel',NULL,8500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hard Drive 8TB',NULL,6500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('ColorVu 4MP',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Switch POE 16 Port',NULL,2800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Point of Sale SP-2500 Series','Intel Celeron (R) CPU J1900 @1.99GHz 4GB RAM, 80GB Storage, 2 Screens on Win10',12000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Sollatek Hivoltguard isense - over voltage protection',NULL,1200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('UPS 650v',NULL,1700.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Wifi Extender',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink 3rd Gen Standard Kit','Includes Hardware, Service, Shipping & Handling',16500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link Wifi Extender - WA850RE','Extends wifi signal, provides wired connection',1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink - Handling Fee','Ordering, tracking and Configuration of account',800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Mag Locks','Locks the door',850.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Door Closer Arm','Automatically shuts the door without any human intervention',500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('ZKTeco Mb 10vl Reader','Input for access control and TA',4000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Push to Exit Button','Exit Button',500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('UPS Batteries',NULL,850.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Panasonic PBX','Panasonic KX-TES824 Advanced HyBrid PABX Telephone System with 8Co Lines and 24 Extensions',12000.0,0.0);
