INSERT INTO customers (name,email,phone,address) VALUES ('The Urban Hotel Ndola','jnsinkamba@theurbanhotelgroup.com','0960747455','President Road, Ndola, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Paul Lwiindi','paul.lwiindi@gmail.com','0765960608','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Ernest Mulenga',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('James Kenny',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('StevenLindunda@gmail.com',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('SES Kitwe',NULL,'''+260976739496','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Lyson Phiri','lphiri@criozm.org','''+260966998865','Makeni, Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Pheddy Musowoya',NULL,'''+260 975158347','Solwezi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mofya Abbuty',NULL,'0965848512',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Sunking Limited','jackline.chembe@sunking.com','''+260977992433','Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('National Savings and Credit Bank',NULL,NULL,'Cairo Road, Northend, Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Tilimboyi Singani','singani.tilimboyi@gmail.com','0966357617','St Marcellin, Kalulushi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Arthur Chaponda',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mwemo Investments Ltd','mwemoinvestments02@gmail.com','''+260967252154','Dr Aggrey road, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Nordic Mineral Traders',NULL,'0961825121','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Sparc System Limited',NULL,NULL,'Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Gift Nachibanga',NULL,'0969630233',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Willie Guava',NULL,NULL,'Ndola, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Nigel Handile',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mrs. Pamela kaira',NULL,'0974902133','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Micheal Ngoma','ngomamich@gmail.com','0966510888','Solwezi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Envirofuture Consultancy Services Limited','matamyo@gmail.com','''+260978652214','Choma Avenue, Parklands, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('MTN EBU North','muhoneh@gmail.com',NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Kitwe Teaching Hospital',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Steinweg Group shipping',NULL,NULL,'Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Kadochi',NULL,NULL,'Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('True Mech Limited','true.mech01@gmail.com','0977306340','P.O Box 23335, Kitwe,, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Media Measure',NULL,NULL,'54 The Valley Road, Westcliff,, Johannesburg, South Africa');
INSERT INTO customers (name,email,phone,address) VALUES ('Denis Zimba',NULL,'0964224863','Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Manoj',NULL,NULL,'Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('AMSL Zambia Limited','amitesh.pathak@amsl-zm.com','''+260972669200','Chingola, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('CFB Medical Centre',NULL,'''+260 211 254 398','Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Deborah Kachana',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Chikusi Banda',NULL,'''+260961997907','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Sanford Mvula','mvulasanford@gmail.com','''+260 968 490628','Mufulira, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Timothy Mwale',NULL,'0967304184','St Marcelin, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('HRL Farms',NULL,'260961997919','Luanshya, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Shaarz Cosmetics Kitwe',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Fraser Alexander',NULL,'''+260966681075','Chingola, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Chibesa Nyimbili','nyimbilichibeza@yahoo.com','0976521243','Lusaka, Zambia');
