INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('HP ProBook 460 G11','Product type: Notebo Form factor: Clamshell Processor family: Series 1 Intel Core Ultra 5 Processor model: 125U Processor frequency: 1.30 / 4.30 GHz (12MB Cache, 12 Cores) NPU: Intel AI Boost, up to 11 TOPS Display diagonal: 35.6 cm (14") HD type: WUXGA Display resolution: 1920 x 1200 pixels Display: Non-Touch, IPS, Anti-glare, 300nits, 45% NTSC Memory: 16 GB 5600 MHz (1 x 16 GB) Memory Type: DDR5-SDRAM Internal drive: 512 GB M.2 PCIe NVMe Storage Type: SSD On-board graphics card model: Intel Graphics Keyboard: HP Premium, Spill resistant, Non-Backlit with numeric keypad Camera: 1080p FHD Fingerprint reader: Yes Operating system: Windows 11 Pro Mobile broadband: Not Supported Product colour: Pike Silver Weight: 1.74 kg Ports 2x USB Type-C 20Gbps signaling rate (USB Power Delivery, DisplayPort 1.4, HP Sleep and Charge) 2x USB Type-A 5Gbps signaling rate (1x charging, 1x power) 1x HDMI 2.1 1x Stereo headphone/microphone combo jack 1x RJ-45',25500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('UniFi Access Points','Ubiquiti U6-LITE UniFi 6 Lite Wi-Fi 6 Dual Band Wireless Access Point',4000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('courier delivery','From Kitwe to Nankonde',1600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('IDS Alarm System',NULL,6000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link Tapo Wifi Camera',NULL,800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('SOLAR PV MOUNTING RAIL P2000 1.0 GI Each 41X41MM 6M',NULL,805.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('END CLAMP 35MM',NULL,29.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('CONNECTOR FEMALE PVMC4 4-6MM/6.5-7.5MM DIAMETER',NULL,102.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('CONNECTOR MALE PVMC4 4-6MM/6.5-7.5MM DIAMETER',NULL,102.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('CABLE SOLAR RED 6MM',NULL,50.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('CABLE SOLAR BLACK 6MM',NULL,50.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('SOLAR DC ARRESTOR','SERIES 750SL, 1100SL OR 2200SLA',760.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('CIRCUIT BRAKER 5KVA',NULL,620.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('CONDUIT PIPE FLEXIABLE 25MM',NULL,24.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Small Splice Box (Includes Pigtails)',NULL,500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Wood Cutting Disc',NULL,50.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of SM Fiber Cable','With 2 Technicians for 3 Hours @ 200 each person per Hour',400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Splicing Services','Per Strand',125.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Accessories, transport and Mobilization',NULL,400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Point Installation',NULL,250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cisco Catalyst C9300L-48P-4X-E','Catalyst 9300L 48 Port 1G Copper with Fixed 4x10G/1G SFP+ Uplinks, PoE+',135000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link EAP610 Outdoor Wireless Coverage','Indoor and outdoor Wireless 6 coverage',5600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Ezviz H8c Cameras','1080p, PTZ, Wireless, outdoor, AI  powered Human detection, motoon tracking, remote monitoring',1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('HiK 4 Channel PoE NVR',NULL,2800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Wall Jack Double','2 Points Connection',0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Wall Jack Single','Single connection',0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Cabinet 4U','All Network devices will be placed',1250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Mobilization',NULL,1000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision Wireless Bridge Kit',NULL,15000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cisco 1900 ISR','Supply and installation for internet connectivity',4000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Mikrotik RB1100AX','RB1100AHx4 is a 13x Gigabit Ethernet ports Router, powered by Annapurna Alpine AL21400 CPU with four Cortex A15 cores, clocked at 1.4GHz each, for a maximum throughput of up to 7.5Gbit',9000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Projector Mounting Bracket',NULL,1200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('HDMI Cable 20m',NULL,900.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('HP Laptop 450 G7','15.6" Laptop – Intel i5-10210U, 16GB RAM, 256GB NVMe SSD, Windows 11 Pro, Intel UHD Graphics, Full HD Display',29500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Desktop G9 HP 290','Core i7, 14 Gen, 8GB RAM, 512GB SSD, 21.5" Monitor with Win 11 Pro + Keyboard and Mouse',26000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link AC1200','TP-Link EAP225-Outdoor |AC1200 Omada Wireless Gigabit Outdoor Access Point',2000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP link CPE 210','Wireless Outdoor Bridge, 300mbps, 9dBi,',2800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hik IP Turrent Camera','4MP Smart Hybrid Light, 2.8mm, POE',2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('MikroTik RB1100AHx4 Router','1100x4 4-cores 1.4Ghz 1Gb RAM 13xGbit LAN',9500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fiber Termination Accessories',NULL,150.0,0.0);
