INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Gigabit media converters',NULL,1560.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fly leads 3m',NULL,150.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Patch cords','5m SC Fiber Patch Cord',60.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fiber installation and splicing',NULL,10320.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Labour data network points installation',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Accessories & Logistics',NULL,12600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Gen 4',NULL,11000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation per Camera',NULL,300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Configuring, Remote viewing and Commissioning',NULL,1050.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Nail in Anchors 6 x 40','Pack of 50',100.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Weather Box (Plastic Casing)','For POE Injectors',350.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Spray Paint',NULL,100.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Stand Fabrication',NULL,350.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Wireless Access Points',NULL,2000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Management system with inventory',NULL,85000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cable RG59 With Power Per Metre',NULL,13.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('PVC Enclosure','To House the Starlink Indoor unit, The POE Injector for the Wireless outdoor unit and the power adaptor',800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('installation of Analogue Camera',NULL,350.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cable laying of CCTV Cameras',NULL,8.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('DVR Initial setup and Configuration','Includes Remote Viewing  Testing & Commissioning',600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fencing Angle Bracket (6 Lines)',NULL,55.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fencing Energizer Wizord 4',NULL,4500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fencing Cable HT 100m Roll',NULL,1400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fencing Braided Wire 5Kg 1.2mm',NULL,700.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fencing Springs Stainless',NULL,65.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fencing Ferrules 6mm',NULL,260.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fencing Lightening Divertor JVA',NULL,260.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Siren 15W',NULL,250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Strobe Light - Big',NULL,250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fencing Earth Spike',NULL,150.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fencing Warning Sign Large',NULL,30.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('siren cable',NULL,6.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Glue 50Ml',NULL,30.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fencing Soft Wire',NULL,120.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Conduits 20mm Black',NULL,20.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Couplings',NULL,10.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Bends',NULL,10.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Electric Fence',NULL,75.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Camera Cleaning and Inspection',NULL,150.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Materials Used for Repair','''-Pair for CCTV Balun X 2  -20m UTP Cable',300.0,0.0);
