INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('32mm HDPE Protective Duct – Site Entry',NULL,50.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Aerial-to-Underground Pipe Support',NULL,1200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cable Suspension & Installation','ncluding Site Survey, Project Management & Hardware Installation',72400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fiber Splicing – 24-Core System',NULL,90.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Patch Panel Installation',NULL,2000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cat6 UTP Cable, Oxygen Free 500m Outdoor',NULL,7500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation and Accessories',NULL,2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Site Survey','Site Survey: Use the Starlink App’s “Check for Obstructions” tool to identify optimal installation points. Ensure a clear line of sight to the sky, free from trees, buildings, or poles.',200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hardware Setup','Assemble and mount the dish securely. Connect dish to power supply and router. Ensure vertical alignment for optimal satellite tracking. Connect to the STARLINK WiFi network. Ethernet cable termination POE adapter to Dish. Provide Cable if cable too short. Max 80m Configure router settings via the Starlink App. Test via provided IPs for Service',1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Configuration','L3 / L2 / MPLS - Remote and Local configurations to be completed. Training to be provided for configurations',350.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Transport within Lusaka and CB',NULL,400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Transport outside Lusaka and CB',NULL,10.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('MikroTik hAP AX',NULL,3600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('RJ45 Boots',NULL,8.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('XGS 108 Appliance',NULL,40000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dahua Wireless Transmission Device (DH-PFWB5-30ac)',NULL,6000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dahua Outdoor Wireless Transmission CPE Network Device V-Radio 5GHz Bridge',NULL,3000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Wooden Poles 16meters',NULL,10000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cambium 425',NULL,7500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cambium ePMP Force 300-16',NULL,5500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Camera and cable setup',NULL,400.0,0.0);
