INSERT INTO customers (name,email,phone,address) VALUES ('Babcock Zambia Limited','smeedy.kapembwa@babcock.co.zm','''+260212216200',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Cindys Creamy Creations','chilima2014@gmail.com','0972888575',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Cindy Creamy Creation','thierry9chilima@gmail.com','0979999249',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Lynot Tangai',NULL,'''+260961997919',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Brian  Mulenga',NULL,'''+260 97 8262442',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Kampeni','mkampeni@gmail.com','''+260961652432','Mufulira, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Nkana Golf Club','accounts@nkanagolfclub.co.zm','''+260978996649','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Gertmark','mireille.ngonga@gertmark.co.zm','''+260966700844',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('IES Zambia','accounts@ieszambia.com','0961874913','Heavy Industrial Area,, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Spring Seeds','springseedszambia@gmail.com','0977838148','Nkana West, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. John Chiwele',NULL,'''+260 212 247005','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Wonder Land Playground','zeliamwaledubovik@gmail.com','''+260 96 8829702','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Milne Mataife','milnecmataifa@yahoo.com',NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Eritaz Networking Engineering','eric@eritaznetworking.com','''+260977584160','Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. George Kabunda',NULL,'0962377900',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Ebogra Engineering','ebograengineering@gmail.com','0961960252',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Lovemore Daka','dakalovemore@hotmail.com','0976828570',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Mercury Express Logistics','ithelpdeskcb@mercury.co.zm','''+260971612959','Nkana East, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Grey Matter Zambia',NULL,'Hamid','Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Anthony Chintu',NULL,NULL,'Chililabombwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Kaambwa Michelo',NULL,'''+260966853578','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Roan Copper Concentrator - Jubilee Metals Group','mwaba.mwachiyaba@sablezinc.co.zm',NULL,'Ndola, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('SAI CRIO','lphiri@criozm.org','''+260 96 6998865','Makeni, Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Kumbaya Gardens & Events',NULL,'0977701837','Kalulushi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Highlands Zambia Ltd','amg2977@gmail.com','0966858515','Heavy Industrial Area, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Emmanuel Malema',NULL,'''+260972834865','Mufulira, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Kasumwa Enviroconsult','mwalevivian@gmail.com','''+260 97 9941715','Riverside, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Artem',NULL,NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Ticheze Lodge & Car Hire',NULL,NULL,'Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Andre Fateev',NULL,'''+61 457 262 432',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Chisha',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Chiluba Yenga',NULL,NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Chiluba Yenga',NULL,'0965540871','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Kano Dental Clinic','clinic@kanodentallimited.com','''+260962167138','Kwacha Road, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Kitwe Surgery Limited','drwezisunkutu@gmail.com','''+260977518949','City Sq,, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mwelwa Mulenga',NULL,'''+260 966 385979','Ndeke, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Bread of Life Church Kitwe','mebbinchiyangi@gmail.com','0973850850','Nkana East, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Family Legacy International',NULL,'096 5845100','Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Buntingwa Resources Limited',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Vincent Nyirenda','tymuorigins@gmail.com',NULL,'kalulushi, Zambia');
