INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Fikansa',NULL,NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Queen P''s Event Centre',NULL,NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Musiwa / Forte Villa Isoka','martinwandira@gmail.com',NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Mpika Client','martinwandira@gmail.com',NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Alstralz Technologies','mwizu.sikanyika@alstralz.com',NULL,'Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Loctaguna Organics','martinwandira@gmail.com',NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Nakonde Town Council',NULL,NULL,'Nakonde, Muchinga Province, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Phil Harold',NULL,'''+260-961022033','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Hellen Bwalya',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Tripump Zambia',NULL,NULL,'Kitwe , Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Fundlink Capital Limited','finance@fundlink.co.zm',NULL,'Lyness House, Freedom Avenue, Kitwe , Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Nchelenge Town Council',NULL,NULL,'Nchelenge , Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Cipo Mbozi',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Wallace Tembo',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Ngangula Nchaba',NULL,NULL,'Solwezi');
INSERT INTO customers (name,email,phone,address) VALUES ('Kasama District Health Office',NULL,NULL,'Kasama, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mwabu Vundamina',NULL,'''+260-965822000','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Engineering Institute of Zambia',NULL,'''+260-211255161','Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Dr. Buleti Nsemukila',NULL,NULL,'Chiengi , Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('A Plus Insurance',NULL,NULL,'Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Choma Municipal Council',NULL,NULL,'Choma, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mumbwa Town Council',NULL,NULL,'Mumbwa, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Customer X',NULL,NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Daniel''s Auto Spares',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Debora Mwababa',NULL,NULL,'Nakonde, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Juan Ocampo',NULL,'''+260-963473008','Riverside, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Hightech Diagnostic Centre Limited','terci.ltd@gmail.com',NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Ascend Futures Foundation',NULL,'''+260-962725873','Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Katie-Marie Limited',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Elsewedy Electric Zambia Ltd',NULL,NULL,'Ndola, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Livingstone City Council',NULL,NULL,'Livingstone , Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('One Cloud Apartments',NULL,NULL,'Nkana West, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Touchnet Investment Ltd',NULL,'''+260-977442644','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Rex Mboneka',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Power Drive Transmission Suppliers Limited',NULL,NULL,'Mkushi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Sanket Sunsol imaging services',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('IES',NULL,NULL,'Chibuluma Road, Kitwe, Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Julius Chimasa',NULL,'''+260-966451491','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('University of Edenberg',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Power Drive Transmission Supplies Ltd',NULL,NULL,'Kitwe, Zambia');
