INSERT INTO customers (name,email,phone,address) VALUES ('Lutaba Mini Hospital',NULL,NULL,'Mwandi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Kalulushi Trust School',NULL,NULL,'Kalulushi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Fibercom Zambia',NULL,NULL,'Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mr. Thindwa',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('IPSOS',NULL,'0965088315','Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Byron Smeeton',NULL,NULL,'Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Dr. Machai',NULL,NULL,'Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Kalonga Logistics',NULL,NULL,'Lumwana, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Muka Staytel',NULL,NULL,'Ndola, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Henry Courtyard',NULL,NULL,'Mansa, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Milne Mataifa','milnecmataifa@yahoo.com','''+260967820413','Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Starlink Customer',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Lucha Apartments',NULL,NULL,'Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('BetAfrica',NULL,NULL,'Kalulushi, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Shaarz Lewanika Mall',NULL,'''+260 973237940','Woodlands Stadium,, Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Shaarz East Park Mall',NULL,'''+260967962090','Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Shaarz Cosmetics Limited',NULL,NULL,'Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Ashfield Resources (Z) Ltd','martinwandira@gmail.com',NULL,'Rhodespark, Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('GS Cash Advance Zambia','martinwandira@gmail.com',NULL,'Woodlands, Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Mrs. Florence Mumba',NULL,NULL,'Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Saro Agro Industrial Limited','caesar@saroagri.co.zm','0979598282','Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('MAQ Millers Limited',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Insightspark Consulting',NULL,'''+260978980921',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Sara Rose Children foundation',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Wils Hotel','moisekn@gmail.com','0979277558',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('ZRA','bwalyak@zra.org.zm','''+260978981384','Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Soka Gakai Zambia',NULL,NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Nandi Mlotshwa','nandimlot@gmail.com','''+260-977522588',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Lilanda Abishai','lilanda.abishai@yahoo.co.uk','''+260-0977416402',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Ms. Mkandawire Sokoni',NULL,NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Audrey Chibuula',NULL,NULL,'Mumbwa Road, Lusaka, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('Reliant Drilling Kitwe','martinwandira@gmail.com',NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Choma Residence','martinwandira@gmail.com',NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Kazilimani_Residence','martinwandira@gmail.com','''+260-978981502',NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('St Michaels Catholic',NULL,NULL,'Kitwe, Zambia');
INSERT INTO customers (name,email,phone,address) VALUES ('JTI Zambia',NULL,NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('CCO',NULL,NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Zhongmei',NULL,NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Martha Cousin',NULL,NULL,NULL);
INSERT INTO customers (name,email,phone,address) VALUES ('Chibesakunda Residence',NULL,NULL,NULL);
