const lines=document.getElementById('lines');let selectedCustomer=null,rows=[],additionalCosts=[];
const money=n=>'K'+Number(n||0).toLocaleString('en-ZM',{minimumFractionDigits:2,maximumFractionDigits:2});
async function search(e,q){const r=await fetch(`${e}?q=${encodeURIComponent(q)}`);return r.ok?r.json():[]}
function menu(a,input,pick){document.querySelector('.suggestions')?.remove();if(!a.length)return;const b=document.createElement('div');b.className='suggestions';Object.assign(b.style,{position:'absolute',zIndex:10,background:'#fff',border:'1px solid #dbe5e4',borderRadius:'8px',width:'100%'});a.forEach(x=>{const z=document.createElement('button');z.type='button';z.textContent=x.name;Object.assign(z.style,{display:'block',width:'100%',padding:'10px',border:0,background:'#fff',textAlign:'left'});z.onclick=()=>{pick(x);b.remove()};b.appendChild(z)});input.parentElement.style.position='relative';input.parentElement.appendChild(b)}
function render(){if(!lines)return;lines.innerHTML=rows.length?rows.map((r,i)=>`<tr><td>${r.description||r.name}</td><td><input class="qty" data-i="${i}" type="number" min="1" value="${r.quantity||1}"></td><td>${money(r.selling_price)}</td><td class="cost">${money(r.internal_cost)}</td><td class="profit">${money((r.selling_price-r.internal_cost)*(r.quantity||1))}</td><td><button type="button" data-remove="${i}">×</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">No items added yet. Search for an item above.</td></tr>';lines.querySelectorAll('.qty').forEach(e=>e.onchange=()=>{rows[e.dataset.i].quantity=Number(e.value)||1;render()});lines.querySelectorAll('[data-remove]').forEach(e=>e.onclick=()=>{rows.splice(e.dataset.remove,1);render()});updateSummary()}
function updateSummary(){const s=rows.reduce((x,r)=>x+(r.quantity||1)*r.selling_price,0),c=additionalCosts.reduce((x,r)=>x+r.amount,0),p=rows.reduce((x,r)=>x+(r.quantity||1)*(r.selling_price-r.internal_cost),0),v=[...document.querySelectorAll('.quote-summary .summary-row strong')];if(v[0])v[0].textContent=money(s);if(v[1])v[1].textContent=money(c);if(v[2])v[2].textContent=money(p);const t=document.querySelector('.summary-total strong');if(t)t.textContent=money(s+c)}
function addAdditionalCost(){const d=prompt('Additional cost description');if(!d)return;const a=Number(prompt('Amount (K)')||0);if(a)additionalCosts.push({description:d,amount:a});updateSummary()}
async function saveQuotation(){const i=document.querySelectorAll('.quote-meta input'),n=i[1]?.value||'QT-'+Date.now(),d=i[2]?.value||new Date().toISOString().slice(0,10),v=Number(document.querySelector('.quote-meta select')?.value?.match(/\d+/)?.[0]||30),r=await fetch('/api/quotations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({quote_number:n,customer_id:selectedCustomer?.id||null,quote_date:d,validity_days:v,lines:rows,additional_costs:additionalCosts})}),x=await r.json();if(!r.ok)return alert(x.error||'Could not save quotation');alert(`Quotation saved: ${n}`)}
const ci=document.getElementById('customer-search');if(ci)ci.oninput=async()=>{if(ci.value.trim().length<2)return;menu(await search('/api/customers',ci.value.trim()),ci,c=>{selectedCustomer=c;ci.value=c.name;ci.disabled=true;ci.parentElement.parentElement.querySelector('small').textContent='Customer selected ✓'})};const ii=document.getElementById('item-search');if(ii)ii.oninput=async()=>{if(ii.value.trim().length<2)return;menu(await search('/api/items',ii.value.trim()),ii,x=>{rows.push({...x,description:x.name,quantity:1});ii.value='';render()})};document.querySelector('.quote-actions .primary')?.addEventListener('click',saveQuotation);document.querySelector('.additional')?.addEventListener('click',addAdditionalCost);const p=document.getElementById('report-period'),pl=document.getElementById('period-label');if(p&&pl)p.onchange=()=>pl.textContent=p.value.toLowerCase();if(document.querySelector('.quote-meta input[type=date]'))document.querySelector('.quote-meta input[type=date]').valueAsDate=new Date();render();
const recent=document.querySelector('.recent-quotes tbody');if(recent)fetch('/api/quotations').then(r=>r.json()).then(a=>{if(a.length)recent.innerHTML=a.map(q=>`<tr><td>${q.quote_number}</td><td>${q.customer_name||'—'}</td><td>${q.quote_date}</td><td>${q.status}</td><td>${money(q.total)}</td></tr>`).join('')}).catch(()=>{});
