const $=id=>document.getElementById(id),money=n=>"K"+Number(n||0).toLocaleString("en-ZM",{minimumFractionDigits:2,maximumFractionDigits:2});
const state={invoices:[],view:"all",search:"",page:1,size:25};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const today=()=>new Date().toISOString().slice(0,10);
function effectiveStatus(i){if(!["Paid","Void","Draft"].includes(i.status)&&Number(i.balance_due)>0&&i.due_date<today())return"Overdue";return i.status||"Draft"}
function filtered(){const q=state.search.toLowerCase();return state.invoices.filter(i=>[i.invoice_number,i.order_number,i.customer_name,i.subject].some(v=>String(v||"").toLowerCase().includes(q))).filter(i=>{const s=effectiveStatus(i).toLowerCase();if(state.view==="all")return true;if(state.view==="unpaid")return Number(i.balance_due)>0&&!['void','draft'].includes(s);return s===state.view})}
function drawSummary(){const now=today(),limit=new Date();limit.setDate(limit.getDate()+30);const within=limit.toISOString().slice(0,10),open=state.invoices.filter(i=>!["Paid","Void"].includes(effectiveStatus(i)));$("receivable-total").textContent=money(open.reduce((s,i)=>s+Number(i.balance_due||0),0));$("due-today").textContent=money(open.filter(i=>i.due_date===now).reduce((s,i)=>s+Number(i.balance_due||0),0));$("due-month").textContent=money(open.filter(i=>i.due_date>now&&i.due_date<=within).reduce((s,i)=>s+Number(i.balance_due||0),0));$("overdue-total").textContent=money(open.filter(i=>i.due_date<now&&!['Draft'].includes(i.status)).reduce((s,i)=>s+Number(i.balance_due||0),0));const paid=state.invoices.filter(i=>i.status==="Paid");$("average-days").textContent=paid.length?"Recorded":"—"}
function draw(){drawSummary();const all=filtered(),pages=Math.max(1,Math.ceil(all.length/state.size));state.page=Math.min(state.page,pages);const rows=all.slice((state.page-1)*state.size,state.page*state.size);$("invoice-list").innerHTML=rows.length?rows.map(i=>{const status=effectiveStatus(i);return`<tr><td>${esc(i.invoice_date)}</td><td><a class="invoice-number-link" href="new-invoice.html?id=${i.id}">${esc(i.invoice_number)}</a></td><td>${esc(i.order_number||"—")}</td><td>${esc(i.customer_name||"—")}</td><td><span class="invoice-status ${status.toLowerCase()}">${esc(status)}</span></td><td>${esc(i.due_date)}</td><td>${money(i.total)}</td><td>${money(i.balance_due)}</td><td class="customer-actions"><a href="new-invoice.html?id=${i.id}">Edit</a><button data-status-id="${i.id}" data-status="${status==='Void'?'Draft':'Void'}">${status==='Void'?'Restore':'Void'}</button><button class="delete" data-delete-invoice="${i.id}">Delete</button></td></tr>`}).join(""):'<tr><td colspan="9" class="empty-state">No invoices found in this view.</td></tr>';const first=all.length?(state.page-1)*state.size+1:0,last=Math.min(state.page*state.size,all.length);$("invoice-page-label").textContent=`${first}–${last} of ${all.length}`;$("invoice-top-page").textContent=`Page ${state.page} of ${pages}`;$("invoice-total-count").textContent=`Total count: ${all.length}`;$("invoice-count").textContent=`${all.length} invoice${all.length===1?"":"s"}`;$("invoice-prev").disabled=state.page<=1;$("invoice-next").disabled=state.page>=pages}
async function load(){const r=await fetch('/api/invoices'),data=await r.json();if(!r.ok)return alert(data.error||'Could not load invoices. Run migration-invoices.sql in D1 first.');state.invoices=data;draw()}
async function patchStatus(id,status){const r=await fetch('/api/invoices',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})}),data=await r.json();if(!r.ok)return alert(data.error||'Could not update invoice');await load()}
$("invoice-search").oninput=e=>{state.search=e.target.value;state.page=1;draw()};$("invoice-page-size").onchange=e=>{state.size=Number(e.target.value);state.page=1;draw()};$("invoice-prev").onclick=()=>{state.page--;draw()};$("invoice-next").onclick=()=>{state.page++;draw()};
$("invoice-view-toggle").onclick=()=>$("invoice-view").classList.toggle("open");$("invoice-view-search").oninput=e=>document.querySelectorAll('[data-invoice-view]').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(e.target.value.toLowerCase()));document.querySelectorAll('[data-invoice-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.invoiceView;state.page=1;$("invoice-view-label").textContent=b.textContent;document.querySelectorAll('[data-invoice-view]').forEach(x=>x.classList.toggle('selected',x===b));$("invoice-view").classList.remove('open');draw()});
$("invoice-list").onclick=async e=>{const id=Number(e.target.dataset.statusId),del=Number(e.target.dataset.deleteInvoice);if(id&&confirm(`${e.target.dataset.status} this invoice?`))await patchStatus(id,e.target.dataset.status);if(del&&confirm('Delete this invoice?')){const r=await fetch(`/api/invoices?id=${del}`,{method:'DELETE'}),data=await r.json();if(!r.ok)return alert(data.error||'Could not delete invoice');await load()}};
load();
