const $=id=>document.getElementById(id),money=n=>"K"+Number(n||0).toLocaleString("en-ZM",{minimumFractionDigits:2,maximumFractionDigits:2}),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const state={items:[],selected:new Set(),view:"all",search:"",page:1,size:25};
function filtered(){const q=state.search.toLowerCase();return state.items.filter(i=>[i.name,i.description,i.purchase_description,i.sku].some(v=>String(v||"").toLowerCase().includes(q))).filter(i=>{const status=i.status||"Active",type=i.item_type||"Goods";if(state.view==="all")return true;if(state.view==="active")return status==="Active";if(state.view==="inactive")return status==="Inactive";if(state.view==="goods")return type==="Goods";if(state.view==="services")return type==="Service";if(state.view==="low-stock")return type==="Goods"&&Number(i.quantity||0)<=5;return true})}
function pageRows(){const all=filtered(),pages=Math.max(1,Math.ceil(all.length/state.size));state.page=Math.min(state.page,pages);return{all,pages,rows:all.slice((state.page-1)*state.size,state.page*state.size)}}
function draw(){const{all,pages,rows}=pageRows();$("items-list").innerHTML=rows.length?rows.map(i=>{const margin=Number(i.selling_price||0)-Number(i.internal_cost||0),pct=Number(i.selling_price)>0?margin/Number(i.selling_price)*100:0;return`<tr class="${state.selected.has(i.id)?'selected-row':''}"><td><input type="checkbox" data-select-item="${i.id}" ${state.selected.has(i.id)?'checked':''}></td><td><a class="item-name-link" href="new-item.html?id=${i.id}">${esc(i.name)}</a>${i.sku?`<small>${esc(i.sku)}</small>`:''}</td><td>${esc(i.item_type||'Goods')}</td><td>${esc(i.unit_of_measure||'Each')}</td><td class="item-description-cell">${esc(i.purchase_description||'—')}</td><td>${money(i.internal_cost)}</td><td class="item-description-cell">${esc(i.description||'—')}</td><td>${money(i.selling_price)}</td><td class="${margin>=0?'positive':'negative'}">${money(margin)} <small>${pct.toFixed(1)}%</small></td><td><span class="customer-status ${String(i.status||'Active').toLowerCase()}">${esc(i.status||'Active')}</span></td><td class="customer-actions"><a href="new-item.html?id=${i.id}">Edit</a><button class="delete" data-delete-item="${i.id}">Delete</button></td></tr>`}).join(''):'<tr><td colspan="11" class="empty-state">No items found in this view.</td></tr>';const first=all.length?(state.page-1)*state.size+1:0,last=Math.min(state.page*state.size,all.length);$("items-page-label").textContent=`${first}–${last} of ${all.length}`;$("item-top-page").textContent=`Page ${state.page} of ${pages}`;$("items-total-count").textContent=`Total count: ${all.length}`;$("item-count").textContent=`${all.length} item${all.length===1?'':'s'}`;$("items-prev").disabled=state.page<=1;$("items-next").disabled=state.page>=pages;$("items-select-page").checked=rows.length>0&&rows.every(i=>state.selected.has(i.id));$("item-bulk-toolbar").hidden=state.selected.size===0;$("item-standard-toolbar").hidden=state.selected.size>0;$("items-selected-count").textContent=`${state.selected.size} selected`}
async function api(method,body,url='/api/items'){const r=await fetch(url,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined}),data=await r.json();if(!r.ok)throw new Error(data.error||'Action failed');return data}
async function load(){try{state.items=await api('GET');draw()}catch(e){alert(e.message)}}
async function status(value){try{await api('PATCH',{action:'status',value,ids:[...state.selected]});state.selected.clear();await load()}catch(e){alert(e.message)}}
$("item-search").oninput=e=>{state.search=e.target.value;state.page=1;draw()};$("items-page-size").onchange=e=>{state.size=Number(e.target.value);state.page=1;draw()};$("items-prev").onclick=()=>{state.page--;draw()};$("items-next").onclick=()=>{state.page++;draw()};$("items-select-page").onchange=e=>{pageRows().rows.forEach(i=>e.target.checked?state.selected.add(i.id):state.selected.delete(i.id));draw()};$("items-list").onchange=e=>{const id=Number(e.target.dataset.selectItem);if(id){e.target.checked?state.selected.add(id):state.selected.delete(id);draw()}};
$("item-view-toggle").onclick=()=>$("item-view").classList.toggle('open');$("item-view-search").oninput=e=>document.querySelectorAll('[data-item-view]').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(e.target.value.toLowerCase()));document.querySelectorAll('[data-item-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.itemView;state.page=1;state.selected.clear();$("item-view-label").textContent=b.textContent;document.querySelectorAll('[data-item-view]').forEach(x=>x.classList.toggle('selected',x===b));$("item-view").classList.remove('open');draw()});
$("items-clear-selection").onclick=()=>{state.selected.clear();draw()};$("items-activate").onclick=()=>status('Active');$("items-inactivate").onclick=()=>status('Inactive');$("items-delete").onclick=async()=>{if(!confirm(`Delete ${state.selected.size} selected item(s)?`))return;try{await api('DELETE',null,`/api/items?ids=${[...state.selected].join(',')}`);state.selected.clear();await load()}catch(e){alert(e.message)}};$("items-list").onclick=async e=>{const id=Number(e.target.dataset.deleteItem);if(id&&confirm('Delete this item?')){try{await api('DELETE',null,`/api/items?id=${id}`);state.selected.delete(id);await load()}catch(err){alert(err.message)}}};load();
