BEGIN TRANSACTION;
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of TV Screen',NULL,1200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Galvanized Tension Spring',NULL,500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Siren Outdoor','Alarm condition when the electric fence has been tampered with.',450.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Mounting Kit','Pole Mount stand, adjustable, anti-corrosion coated',1000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Management Services',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Square tubes 50*50*3mm',NULL,385.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cutting disc',NULL,75.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Welding lodes',NULL,575.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('3core cable 2.5mm',NULL,44.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Red oxide paint',NULL,450.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Thinners',NULL,375.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Steel Saddle',NULL,20.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('PVC Conduit Bends',NULL,300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('⁠Gate Wheel’s 100ts',NULL,600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('D6 Smart Gate Motor',NULL,14000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('HP Printer Smart Tank 520 All-in-One series',NULL,6200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Ubiquiti U6+ Wi-Fi 6 Dual-Band Access Point',NULL,6500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Switch Unmanaged 8 Port',NULL,1200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Technician Installation and labour','2 Installation Technicians perfroming; Physical installation, cabling, termination, camera mounting',140.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Logistics',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Supervisor Installation','System design, supervision, testing, client handover',220.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Camera Installation (Per Camera)',NULL,350.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cable Laying (per meter)',NULL,8.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('DVR/NVR Setup',NULL,400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Remote Viewing Setup',NULL,250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Testing, Aligning and Commissioning',NULL,200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Transport per',NULL,8.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Training and Handover',NULL,200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Supply & Install Outdoor Hikvision WAP','DS-3WAP623E-SI',7500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Stands',NULL,1050.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Momo Charges',NULL,300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cisco ISR 4321','(1) Chassis with (2) GE Data Ports, (1) GE MGMT Port, (2) NIM Slots, (1) ISM Slot, and AC Power Supply',75000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Legrand RJ45 Data Inserts',NULL,264.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Wall mount RJ45 data boxes',NULL,180.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Data patch panels',NULL,900.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fiber patch panels',NULL,1560.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Brush Panel',NULL,240.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunking PVC 60x40',NULL,420.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Floor trunking',NULL,420.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fiber cabe PVC duct roll',NULL,1800.0,0.0);
COMMIT;
