BEGIN TRANSACTION;
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cabinet 9U  Cabinet',NULL,3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Mini Kit','Satellite internet kit delivering high-speed, low-latency connectivity anywhere.',7500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink LAN Adapter','Converts Wifi to Cable from the Standard Starlink Unit',2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP-LInk AC1200',NULL,1800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link Ceiling Mount WiFi EAP223','Ceiling Mounted, POE, upto 1.7mbps, Gigabyte Ethernet connection, Mesh Capable, 5Ghz/2.4Ghz wifi',1800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Cabinet 6U','Main Network Cabinet',3000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('PVC Rack for POE Switch and Camera Terminations','Switch with Power Socket Ideal for 4/8 Channel CCTV System for Both Indoor and Outdoor Purpose, Size 17X15X6 Inch',1600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Ubiquiti UAP-AC-M-5 Mesh WiFi AC1300','Omni Direction wifi Coverage',4500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cisco  Catalyst 9300-24P','24 × 1G PoE+ ports, 1RU, dedicated mgmt, console, VLANs, enterprise MTBF',265000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Bracket',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Stand',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cisco 880 Router','Routing and VPN ipsec handling',7000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision NVR 32 channel',NULL,9000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 32 Channel NVR',NULL,9000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Gen 3 Standard',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Activation',NULL,3000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Unmanaged POE Switch 16 Port',NULL,4000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fiber patch cords',NULL,150.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fiber Patch Panel',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Power cable 2.5mm x 3 Core flex',NULL,40.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Circuit Breaker 10Amp',NULL,150.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Fiber optic',NULL,20.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Cameras and Cable',NULL,1200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Splicing fiber',NULL,150.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of power extensions',NULL,2000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Network Cabinet',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Configuration and handover',NULL,3000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Radios',NULL,6400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Gen 3 version 4','Satellite internet kit delivering high-speed, low-latency connectivity anywhere.',9500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('2MP Fixed Bullet Camera - Tiandy','I3/Y/2.8(4)mm',450.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('H.265 1HDD 4vch PSE NVR - Tiandy','I/B/P4/L/S',1000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation  Acces',NULL,200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Configuration and Installation of Deco Wifi Mesh',NULL,600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Cable UTP Cat 6','Twisted Pair',15.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Corporate Subscription',NULL,1300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Starlink Mini',NULL,2000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('P520 PBX','Yeaster P-Series P520 PBX System (Excl. Addons)',15990.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Yealink T31W SIP Phone','Yealink SIP-T31W Desktop IP Phone with built-in Wi-Fi, 10/100Mb Ethernet, includes PSU',4500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fanvil Phones 2SIP',NULL,2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation of Starlink',NULL,2000.0,0.0);
COMMIT;
