BEGIN TRANSACTION;
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fiber Converters SM 1000/100 Speed',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 4 Network Video Recorder',NULL,2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hisense 32 Inch LED TV',NULL,3250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Accomodation',NULL,2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunking PVC 50x75',NULL,360.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunking 50x50',NULL,220.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunking 25x38',NULL,150.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunking PVC 16x25',NULL,120.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunking PVC 16x16',NULL,100.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunking PVC 25x38',NULL,600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('DC (Cigarette Cable)',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Mini Magnetic (Car Mount/Metal)',NULL,4500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('EZVIZ H3c 2K Smart WiFi Camera',NULL,1300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link EAP610 Indoor Wireless',NULL,5900.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link Deco M4','Pack of 3',2850.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Switch Unmanaged 24 Port',NULL,3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Repair Tools',NULL,2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dual SATA HDD/SSD Docking Station',NULL,1650.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Portable Blocker',NULL,1400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Powerology Portable Power Station - 300W','Pater I - Starlink Gen 2/3 has 3-4.5 Hours',10500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Powerology Portable Power Station - 700W','Pater II Standard Starlink Gen 2/3 has 6.5 -8 hours run time',12500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Powerology Portable Power Station - 1200W','Pater III Starlink Standard Gen 2/3 with 13-16 Hours run time',17500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link Tapo C200 Indoor Camera','080p Full HD indoor security camera with pan/tilt functionality, night vision, motion detection, two-way audio, and remote viewing via the Tapo mobile app. Supports local storage via microSD card.',750.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link Tapo C520WS','MP Outdoor Pan/Tilt Wi-Fi Security Camera featuring 2K QHD video resolution, 360° coverage, color night vision, AI motion detection, two-way audio, IP66 weatherproof design, remote monitoring via Tapo App, and local microSD storage support.',1600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Activation',NULL,500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Samsung Galaxy Tab A11','Samsung Galaxy Tab A11 8.7" Android Tablet, 4GB RAM, 64GB Storage, Wi-Fi, 90Hz - Screen Protector -Protective Pouches/Cases -45W Charger with USB Cable',4500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('P520 Yeastar P-Series P520 PBX System (Excl. Addons)','[1YPBXP520]',15000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fanvil V60W Fanvil V60W Prime Wi-Fi 6 IP Phone','[3FV60W]',2600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fiber Suspension Clamps',NULL,1600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Patch Panel',NULL,2000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation, Securing and Tensioning of Fiber',NULL,40000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Pig Tails',NULL,25.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fibre Support Poles 12m',NULL,5500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fibre Tension/Dead-End Clamps',NULL,550.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Transportation & Logistics - Poles and Installation material',NULL,20000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('24-Core Joint Box - Complete','24F Fiber Optic Closure Assembly',2000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('24-Core Fiber Distribution Panel (ODF)','Cross Connect Unit',4200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Tension/Dead-End Clamps Fiber tension',NULL,550.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Down Lead Clamp',NULL,50.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fiber Storage Unit',NULL,900.0,0.0);
COMMIT;
