BEGIN TRANSACTION;
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Pole/Bracket',NULL,2000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Installation','1 Technician @300 per hour',300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Optic Fibre',NULL,22.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('HiKvision DVR Kit 8 Channels',NULL,6500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Monitoring Screen 42"',NULL,8000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('PVC Conduit Pipes','3 meters per conduit pipe',460.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('55'''' LG TV Screen with wall mounts',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Sticky Trunking 16 x 25',NULL,220.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 8 CH PoE NVR',NULL,4500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network Switch 16 Port',NULL,3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Standard 3rd Gen Kit','50-250 Mbps speeds, 50-75W power use, Wi-Fi 5, and an IP54-rated weather-resistant design.',10725.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('CCTV Cable RG59 + Power Cable',NULL,14.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link Archer AX10 Wireless Router','AX1500 Wi-FI 6 Router',2850.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Labour - Starlink / WiFi',NULL,4500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('UTP Ethernet Cat 6 Cable','Network Cable',12.5,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Monitoring Screen 24"',NULL,2000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 4 Channel eDVR with eSSD','4 Cameras DVR',6000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link Wireless Access point Ceiling Mount',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink 40GB Residential Plan Starlink 40GB Priority plan','Starlink 40GB Priority Monthly Subscription plan LSK',1690.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Gen 2 Lsk','Starlink Kit and Installation',17000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Subscription Monthly','Priority Package subscription at K1,560 Per Unit',1560.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Gen 3 Mini','IP67-rated satellite internet device with Wi-Fi 5, 25-220 Mbps speeds, and 25-40W power consumption.',8500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Mobilization and Logistics',NULL,500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hik 9 Port POE Auxiliary Network Switch','Powers on end nodes that support POE',1600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Wireless Bridge 5Ghz 300Mbps Point To Point','15km wireless Point to Point',3500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision Dome 2MP IP Camera',NULL,2200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Outdoor UTP Cable (305m)',NULL,7500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TP Link Link AC1200','Includes Network UTP Cable',1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('12 Core Hybrid Power Optic Fiber','6 Pair 1.5mm power',55.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('PTZ IP 100m 4MP 4" ColorVu TandemVu','Hikvision DS-2SE4C425MWG-E(14F0) is a 4MP PTZ IP camera with 25× zoom, ColorVu for low-light clarity, and 100m IR range. It features smart tracking, WDR, and PoE+ support, ideal for large-area surveillance.',12500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fiber Optic 12 Core',NULL,30.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Support Service Charge',NULL,1000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Gen 3 - Activated','Standard Activated Gen 3 Starlink. Starlink Router 15m Starlink Cable Power Cable Standard Mount',15000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Eaton Intruder Alarm System','4 x Motion detector, 3 x door close, 1 x sms communicate',9500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Reader Indoor F18 Biometrics ZK','2.4inch TF LCD Color Screen, 3000 Finger Capacity, 5000 card Capacity, 100000 transaction capacity, ZK Optical Sensor, ZK version 10.0, TCP/IP Communication, wiegand signal input/output',13000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('PSU 12V 5AMP Access Control Securi- Prod - PS49','Input voltage: 190 - 265VAC at 50/60Hz, Battery backup power supply, Lockable enclosure grey epoxy-coated finish',1300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Battery 12V 12AH Securi-Prod - BA13-2 Deep Cycle',NULL,1200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cable 0.5mm RIP Cord White 100m','White 100m',1100.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Emergency Break Glass','Glass Break Green Call Point Resettable - FR02',1200.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('No Touch Exit Button','Exit Sensor No Touch - SW165',1500.0,0.0);
COMMIT;
