BEGIN TRANSACTION;
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision PTZ 150m Analogue',NULL,9000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 16 channel NVR','Digital NVR with ONVIF',8500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Monitoring Screen 50"',NULL,10000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Wireless Mouse',NULL,800.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('HDMI Cable 5m',NULL,600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Wall Box (Weather Box) 600x400',NULL,2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Beetel M71','Analogue Handset',750.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision NVR with Monitor, wifi & 8 Channel','DS-768NI-L1/W',16500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Analogue PBX 6 Lines & 16 Extensions','Advanced Hybrid Telephone System 6 Lines,16 Extension PBX',17500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fanvil X1SG Phones','2 SIP Lines, 3 way Audio conference, IP Digital phones.',2750.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Grandstream UCM6202',NULL,20000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 2MP Bullet IP Camera','2.8mm, 1920x1080 resolution, Color VU',1700.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunk PVC 100 X 40','3 meter',600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision Network switch','24 Port Poe CCTV Network Switch',8000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Power Extension',NULL,300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('TV Screen Bracket',NULL,600.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Dahua IP Dome',NULL,1500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Network POE Switch 24 Ports',NULL,5500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hard Drive 4TB',NULL,4500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Starlink Home Installation','Installation of Starlink Kit inclusive of Trunking & wall mount',2500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('RJ45 Connectors',NULL,5.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision 80mm Bullet',NULL,3000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Point to point Pair Radios',NULL,6500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cabinet Network 6u',NULL,3000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('PVC Conduit Pipes Bundle','28 Pipes in the Bunch of 3 meters per conduit pipe',460.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('PVC Bends Bundle','50 Bends per Bundle',500.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Saddles PVC Bunch','50 quantity',300.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Nails Pack','packet of 50 nails',250.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Hikvision NVR 16 Channel IP',NULL,12000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Shielded/Outdoor Cat 6 Cable (2 Rolls)',NULL,8000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('24 Port POE Network Switch',NULL,10000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('M5 Nano Stations Radio',NULL,4000.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('3 core power cable 2.5mm x 100m',NULL,400.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Earth wire cable 2,5mm x 100m x 1 roll',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Fisher Plugs & Screws (Packets)',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Rubber Boots',NULL,4.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Trunkings 75mm X 100mm X 3m',NULL,150.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('PVC 3 way looping box x 25mm',NULL,650.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Adhesive Silicon (20 Pieces)',NULL,0.0,0.0);
INSERT INTO items (name,description,selling_price,internal_cost) VALUES ('Cable ties T400',NULL,0.0,0.0);
COMMIT;
