(()=>{
const $=id=>document.getElementById(id),money=n=>'K'+Number(n||0).toLocaleString('en-ZM',{minimumFractionDigits:2,maximumFractionDigits:2}),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),state={catalog:[],category:'All Reports',search:'',active:null,data:null};
const now=new Date(),localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,today=localDate(now);
function range(preset){let start=new Date(now.getFullYear(),now.getMonth(),1),end=new Date(now.getFullYear(),now.getMonth()+1,0);if(preset==='last-month'){start=new Date(now.getFullYear(),now.getMonth()-1,1);end=new Date(now.getFullYear(),now.getMonth(),0)}if(preset==='this-quarter'){const q=Math.floor(now.getMonth()/3);start=new Date(now.getFullYear(),q*3,1);end=new Date(now.getFullYear(),q*3+3,0)}if(preset==='this-year'){start=new Date(now.getFullYear(),0,1);end=new Date(now.getFullYear(),11,31)}if(preset==='last-year'){start=new Date(now.getFullYear()-1,0,1);end=new Date(now.getFullYear()-1,11,31)}if(preset==='custom')return; $('report-from').value=localDate(start);$('report-to').value=Math.min(end.getTime(),now.getTime())===end.getTime()?localDate(end):today;}
function drawCatalog(){const list=state.catalog.filter(r=>(state.category==='All Reports'||r.category===state.category)&&`${r.name} ${r.category}`.toLowerCase().includes(state.search));$('report-list-title').textContent=state.category;$('report-list-count').textContent=`${list.length} report${list.length===1?'':'s'}`;$('report-catalog').innerHTML=list.length?list.map(r=>`<tr><td><button class="report-open-link" data-report="${esc(r.id)}">${esc(r.name)}</button></td><td>${esc(r.category)}</td><td>System Generated</td><td class="report-last-viewed">—</td></tr>`).join(''):'<tr><td colspan="4" class="empty">No reports match your search.</td></tr>';}
function showReport(id){state.active=state.catalog.find(x=>x.id===id);if(!state.active)return;$('report-catalog-view').hidden=true;$('report-view').hidden=false;$('report-category-label').textContent=state.active.category.toUpperCase();$('report-title').textContent=state.active.name;$('report-preset').value='this-month';range('this-month');run();}
async function run(){if(!state.active)return;const from=$('report-from').value,to=$('report-to').value;if(!from||!to||from>to){alert('Choose a valid date range.');return} $('report-run').disabled=true;$('report-run').textContent='Running…';try{const res=await fetch(`/api/reports?report=${encodeURIComponent(state.active.id)}&from=${from}&to=${to}`),d=await res.json();if(!res.ok)throw Error(d.error||'Could not generate report');state.data=d;renderResult(d)}catch(e){$('report-results-body').innerHTML=`<tr><td class="empty" colspan="10">${esc(e.message)}</td></tr>`}finally{$('report-run').disabled=false;$('report-run').textContent='Run Report'}}
function renderResult(d){$('report-period-label').textContent=`From ${d.from} to ${d.to}`;$('report-generated-note').textContent=`Generated ${new Date(d.generated_at).toLocaleString()}`;const headers=d.columns||[],rows=d.rows||[];$('report-results-head').innerHTML=`<tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr>`;$('report-results-body').innerHTML=rows.length?rows.map(row=>`<tr>${headers.map(h=>{const key=h.replace(/ \(ZMW\)$/,'');let v=row[key]??row[h]??'';const numeric=typeof v==='number';if(numeric&&/(ZMW|Amount|Sales|Received|Balance|Total|Paid|Price|Cost|Value|Tax|Profit)/i.test(h))v=money(v);else if(numeric&&Number.isInteger(v)===false)v=Number(v).toLocaleString('en-ZM',{maximumFractionDigits:2});return `<td>${esc(v)}</td>`}).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length||1}" class="empty">No saved activity found for this date range.</td></tr>`;
const totalIndex=headers.findIndex(h=>/Amount|Sales|Balance|Total|Value|Cost|Profit/i.test(h));if(rows.length&&totalIndex>=0&&state.active.id!=='profit-loss'){const key=headers[totalIndex].replace(/ \(ZMW\)$/,'');let sum=rows.reduce((s,r)=>s+(Number(r[key]??r[headers[totalIndex]])||0),0);if(state.active.id==='profit-loss')sum=0;$('report-results-foot').innerHTML=`<tr><th colspan="${totalIndex||1}">Total</th><th>${money(sum)}</th>${headers.slice(totalIndex+1).map(()=>'<th></th>').join('')}</tr>`}else $('report-results-foot').innerHTML='';const summaries=[];if(d.summary&&Object.keys(d.summary).length){for(const [key,value] of Object.entries(d.summary)){summaries.push(`<div class="report-summary-card"><span>${esc(key.replaceAll('_',' '))}</span><strong>${money(value)}</strong></div>`)}}else if(rows.length){summaries.push(`<div class="report-summary-card"><span>Records</span><strong>${rows.length.toLocaleString()}</strong></div>`)}$('report-summary').innerHTML=summaries.join('')}
function exportCsv(){if(!state.data)return;const cols=state.data.columns,rows=state.data.rows;const csv=[cols,...rows.map(r=>cols.map(c=>r[c.replace(/ \(ZMW\)$/,'')]??r[c]??''))].map(row=>row.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\r\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`${state.active.id}-${state.data.from}-to-${state.data.to}.csv`;a.click();URL.revokeObjectURL(a.href)}
$('report-catalog').onclick=e=>{const b=e.target.closest('[data-report]');if(b)showReport(b.dataset.report)};$('report-search').oninput=e=>{state.search=e.target.value.trim().toLowerCase();drawCatalog()};document.querySelectorAll('.report-category').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;document.querySelectorAll('.report-category').forEach(x=>x.classList.toggle('active',x===b));drawCatalog()});$('reports-back').onclick=()=>{$('report-view').hidden=true;$('report-catalog-view').hidden=false};$('report-preset').onchange=e=>range(e.target.value);$('report-run').onclick=run;$('report-export').onclick=exportCsv;$('report-print').onclick=()=>window.print();
fetch('/api/reports?report=catalog').then(r=>r.json()).then(data=>{state.catalog=data;drawCatalog()}).catch(()=>{$('report-catalog').innerHTML='<tr><td colspan="4" class="empty">Reports could not be loaded. Check the API deployment.</td></tr>'});
})();
