(()=>{
const $=id=>document.getElementById(id),defaults={
 'organization.profile':{organization_name:'Terci Communications Limited',industry:'Telecommunications',country:'Zambia',contact_person:'Terence Chilima',address1:'',address2:'',city:'Kitwe',province:'Copperbelt',postal_code:'',phone:'+260 972 888 575',email:'info@terci.net',website:'https://terci.net',logo_url:'terci-logo.png'},
 'organization.branding':{appearance:'light',accent:'#ed1b2f',keep_branding:'yes'},
 'setup.general':{currency:'ZMW',date_format:'DD/MM/YYYY',default_unit:'Each',quote_validity:'30'},
 'setup.currencies':{base_currency:'ZMW',additional_currencies:'ZMW — Zambian Kwacha'},
 'setup.paymentTerms':{default_term:'Due on Receipt',terms:'Due on Receipt\nNet 7\nNet 15\nNet 30\nNet 60'},
 'taxes.settings':{tax_rates:'Standard Rate — 16%\nZero Rate — 0%\nExempt — 0%',tax_note:'Confirm current tax treatment with your accountant before applying tax to a transaction.'},
 'setup.reminders':{reminder_days:'7, 3, 1',reminder_enabled:'no'},
 'setup.customerPortal':{portal_enabled:'no'},
 'customization.emailNotifications':{quote_copy:'no',invoice_copy:'no',payment_copy:'no'},
 'module.sales':{default_quote_validity:'30',internal_costs:'yes',sales_note:'Purchase costs and profit stay internal to authorised Terci users.'},
 'module.purchases':{default_expense_account:'Purchases',default_paid_through:'Bank Account'},
 'module.general':{default_customer_terms:'Due on Receipt',default_item_unit:'Each'}
};
const pages={
 'organization.profile':{title:'Organization Profile',group:'Organization Settings',desc:'Business details used across Terci One and customer documents.',fields:[['organization_name','Organization Name','text'],['industry','Industry','select',['Telecommunications','Information Technology','Security Services','Retail','Other']],['country','Organization Location','text'],['contact_person','Primary Contact','text'],['address1','Address line 1','text'],['address2','Address line 2','text'],['city','City','text'],['province','Province','text'],['postal_code','Postal code','text'],['phone','Phone','tel'],['email','Email','email'],['website','Website URL','url'],['logo_url','Organization Logo URL','url']]},
 'organization.branding':{title:'Branding',group:'Organization Settings',desc:'Choose the appearance and accent colour used by the application.',fields:[['appearance','Appearance','select',['Light','Dark']],['accent','Accent Colour','color'],['keep_branding','Show Terci branding on documents','select',['yes','no']]]},
 'setup.general':{title:'General Preferences',group:'Setup & Configurations',desc:'Set the standard currency and display defaults for the workspace.',fields:[['currency','Base Currency','select',['ZMW','USD']],['date_format','Date Format','select',['DD/MM/YYYY','YYYY-MM-DD','MM/DD/YYYY']],['default_unit','Default Unit of Measure','text'],['quote_validity','Default quotation validity (days)','number']]},
 'setup.currencies':{title:'Currencies',group:'Setup & Configurations',desc:'Configure currency display preferences. Multi-currency transactions are not yet supported.',fields:[['base_currency','Base Currency','select',['ZMW','USD']],['additional_currencies','Available currency list','textarea']]},
 'setup.paymentTerms':{title:'Payment Terms',group:'Setup & Configurations',desc:'Maintain the payment terms offered to customers. Enter one term per line.',fields:[['default_term','Default Payment Term','select',['Due on Receipt','Net 7','Net 15','Net 30','Net 45','Net 60']],['terms','Payment Terms List','textarea']]},
 'taxes.settings':{title:'Taxes',group:'Taxes & Compliance',desc:'Maintain tax labels for reference. Tax calculation and filing integrations are not enabled yet.',fields:[['tax_rates','Tax Rate List','textarea'],['tax_note','Compliance note','textarea']]},
 'setup.reminders':{title:'Payment Reminders',group:'Setup & Configurations',desc:'Reminder preferences are saved here. Automatic email reminders require an email service connection.',fields:[['reminder_enabled','Enable automatic reminders','select',['no','yes']],['reminder_days','Reminder days before due date (comma separated)','text']]},
 'setup.customerPortal':{title:'Customer Portal',group:'Setup & Configurations',desc:'Customer login and portal access are not connected yet. Keep this disabled until portal authentication is configured.',fields:[['portal_enabled','Customer Portal','select',['no','yes']]]},
 'customization.emailNotifications':{title:'Email Notifications',group:'Customization',desc:'Notification preferences can be stored here. Sending email requires connecting an email provider.',fields:[['quote_copy','Send a copy when a quotation is created','select',['no','yes']],['invoice_copy','Send a copy when an invoice is created','select',['no','yes']],['payment_copy','Send a copy when a payment is recorded','select',['no','yes']]]},
 'module.sales':{title:'Sales Preferences',group:'Module Settings',desc:'Set defaults for quotations and sales documents.',fields:[['default_quote_validity','Default quotation validity (days)','number'],['internal_costs','Show internal costs to authorised users','select',['yes','no']],['sales_note','Internal cost visibility note','textarea']]},
 'module.purchases':{title:'Purchases Preferences',group:'Module Settings',desc:'Set defaults for expense capture.',fields:[['default_expense_account','Default Expense Account','select',['Purchases','Cost of Goods Sold','Fuel & Mileage','Labour','Travel','Office Supplies','Repairs & Maintenance','Other']],['default_paid_through','Default Paid Through','select',['Bank Account','Cash','Mobile Money','Card','Cheque','Other']]]},
 'module.general':{title:'General Module Preferences',group:'Module Settings',desc:'Common defaults for customer, vendor and item entry forms.',fields:[['default_customer_terms','Default Customer Payment Term','select',['Due on Receipt','Net 7','Net 15','Net 30','Net 45','Net 60']],['default_item_unit','Default Item Unit','text']]},
 'organization.ai':{title:'AI Integration',group:'Organization Settings',info:'AI features are not connected to this Terci One workspace yet.'},
 'organization.subscription':{title:'Manage Subscription',group:'Organization Settings',info:'Subscription billing is not configured in this application.'},
 'users.roles':{title:'Users & Roles',group:'Users & Roles',info:'User sign-in and role permissions are not configured yet. The current workspace does not enforce per-user access controls.'},
 'setup.openingBalances':{title:'Opening Balances',group:'Setup & Configurations',info:'Opening balances require an accounting ledger. The current application does not yet post ledger balances.'},
 'customization.numberSeries':{title:'Transaction Number Series',group:'Customization',info:'Quotation, invoice, receipt and credit note numbers are generated by their modules. Number-series controls are not connected to those generators yet.'},
 'customization.pdfTemplates':{title:'PDF Templates',group:'Customization',info:'The current Terci quotation PDF layout is active. Template editing and invoice PDF templates are not yet available here.'},
 'module.onlinePayments':{title:'Online Payment Gateways',group:'Module Settings',info:'Payments are currently recorded manually using Cash, Bank Transfer, Mobile Money, Card, Cheque or Other. No online payment gateway is connected.'},
 'extension':{title:'Integrations & Marketplace',group:'Extensions & Developer Data',info:'No external integrations are configured yet.'},
 'developer':{title:'Developer Data',group:'Extensions & Developer Data',info:'Developer settings and API key management are not available in this workspace.'}
};
let saved={},active='home';
async function load(){try{const r=await fetch('/api/settings'),d=await r.json();if(!r.ok)throw Error(d.error||'Settings could not be loaded');saved=d||{}}catch(e){console.warn('Settings load:',e.message);saved={}}}
function val(key,name){return (saved[key]&&saved[key][name])??(defaults[key]&&defaults[key][name])??''}
function fieldHtml(f,key){const [name,label,type,opts]=f,value=val(key,name);if(type==='textarea')return `<label class="settings-field settings-field-wide">${label}<textarea name="${name}" rows="${name.includes('note')?3:5}">${esc(value)}</textarea></label>`;if(type==='select')return `<label class="settings-field">${label}<select name="${name}">${opts.map(o=>{const v=type==='select'&&['yes','no'].includes(o)?o:o.toLowerCase()==='light'?'light':o.toLowerCase()==='dark'?'dark':o;return `<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(o==='yes'?'Yes':o==='no'?'No':o)}</option>`}).join('')}</select></label>`;return `<label class="settings-field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${name==='organization_name'?'required':''}></label>`}
function open(key){active=key;document.querySelectorAll('.settings-nav [data-setting]').forEach(b=>b.classList.toggle('selected',b.dataset.setting===key));$('settings-home').hidden=true;$('settings-detail').hidden=false;const p=pages[key];if(!p){$('settings-detail').innerHTML='<p class="settings-error">This settings page is unavailable.</p>';return}const fields=p.fields||[];$('settings-detail').innerHTML=`<button class="settings-back" id="settings-back">← All Settings</button><section class="settings-panel"><div class="settings-panel-heading"><span class="eyebrow">${esc(p.group)}</span><h1>${esc(p.title)}</h1><p>${esc(p.desc||p.info||'')}</p></div>${p.info?`<div class="settings-info-box"><b>Not connected yet</b><p>${esc(p.info)}</p></div>`:`<form id="settings-form" data-key="${esc(key)}"><div class="settings-form-grid">${fields.map(f=>fieldHtml(f,key)).join('')}</div><div class="settings-form-actions"><span id="settings-save-status" aria-live="polite"></span><button type="submit" class="primary">Save Settings</button></div></form>`}</section>`;$('settings-back').onclick=home;const form=$('settings-form');if(form)form.onsubmit=save}
function home(){active='home';$('settings-detail').hidden=true;$('settings-home').hidden=false;document.querySelectorAll('.settings-nav [data-setting]').forEach(b=>b.classList.remove('selected'));document.querySelector('.settings-nav-item[data-setting="home"]').classList.add('selected')}
async function save(e){e.preventDefault();const form=e.currentTarget,key=form.dataset.key,settings={...((saved&&saved[key])||{})};for(const [name,value] of new FormData(form).entries())settings[name]=value;if(key==='organization.branding'){document.documentElement.style.setProperty('--red',settings.accent||'#ed1b2f')}const status=$('settings-save-status'),button=form.querySelector('[type=submit]');status.textContent='Saving…';button.disabled=true;try{const r=await fetch('/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({settings:{[key]:settings}})}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not save settings');saved[key]=settings;status.textContent='Saved';setTimeout(()=>{const x=$('settings-save-status');if(x)x.textContent=''},2500)}catch(error){status.textContent=`Could not save: ${error.message}`}finally{button.disabled=false}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.addEventListener('click',e=>{const b=e.target.closest('[data-setting]');if(b){open(b.dataset.setting);return}const close=e.target.closest('#settings-banner-close');if(close)close.parentElement.remove()});$('settings-search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.settings-nav-group').forEach(g=>{let visible=false;g.querySelectorAll('[data-setting]').forEach(b=>{const show=!q||b.textContent.toLowerCase().includes(q);b.hidden=!show;if(show)visible=true});g.hidden=q&&!visible});document.querySelectorAll('.settings-card').forEach(c=>{let count=0;c.querySelectorAll('[data-setting]').forEach(b=>{const show=!q||b.textContent.toLowerCase().includes(q);b.hidden=!show;if(show)count++});c.hidden=q&&!count});document.querySelectorAll('.settings-category-block').forEach(x=>x.hidden=q&&!x.querySelector('.settings-card:not([hidden])'))});load().then(()=>{const branding=saved['organization.branding'];if(branding?.accent)document.documentElement.style.setProperty('--red',branding.accent)});
})();
